name: Release PKG

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Create release  and publish
        uses: changesets/action@v1
        with:
          version: bun run changeset version
          publish: bun run changeset publish
        env:
          # Changesets needs a GitHub token to be able to create a release pull request
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # If you want to publish to npm, you need to set up an npm token, so changesets can publish your packages
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
